### ISSUE TITLE
Auto-fill with reasonable mod value ranges

### ISSUE THREAD

**Issue by saveriodesign** [redSol/PoeTradeSearchEN#11]
I'd prefer, when I `ctrl+C` something, that the searchable modifiers be filled in with a min below the actual value and a max above the actual value, so searches are more likely to yield relevant results. If there is a way to do this from the configuration, I can't discern it from the example.

I'd love to set it to just 80% to 120% so I'm not manually fixing the ranges to try to get hits.

**Comment by JusKillmeQik** [comment]
I like this idea, but the ability to have Uniques stay at the 100% for the minimum value is important to me.  Also the ability to leave maximums off also helps.

**Comment by redSol** [comment]
Added, make sure to replace your config file, or compare the new one to yours.
the new options are called:
min_value_percent
max_value_percent
unique_min_value_percent
unique_max_value_percent
set_max_value

**Comment by saveriodesign** [comment]
It seems that whatever you set the maximum percent to acts on the minimum rather than the base value of the mod.

![image](https://user-images.githubusercontent.com/13221170/72299052-c54ff000-362d-11ea-9d28-aeb8510dd40f.png)

Here, I've set the search to 90-110% in my config, with the actual value of the item's movement speed bonus 30%. The 27 is 90% of 30, check, but 29.7 is 110% of 27, and prevents matches in this case because movement speed bonuses are multiples of 5.

May need to crack this issue back open.
