### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by Helban** [redSol/PoeTradeSearchEN#18]
Hi,

Would it be possible to have the tool auto update and replace it self with new version? 
I love that youre so active in development, so new versions appear every day, and it's a bit tiresome to download and replace by hand every time :D 

While at it, would be great to either merge config changes with what's already there done by the user, or if the merge is problematic, then tell user that automerge was not possible and it should be merged by hand

BR,
Adam

**Comment by redSol** [comment]
Sure, i'll look into it, shouldn't be too hard

**Comment by redSol** [comment]
added

**Comment by Helban** [comment]
@redSol has this been released? If so, it's not working
, still takes to the github page

**Comment by Helban** [comment]
@redSol by "added" you meant added to backlog? ;-)
