### ISSUE TITLE
Add fast kick and fast invite?

### ISSUE THREAD

**Issue by DavidAlcns** [redSol/PoeTradeSearchEN#20]
Kick yourself from the current party. Default keybind should be F4.

This will require the character name to be configured as the command is 
`/kick <playername>`

And for fast trade just like lutbot's a sequence of commands that would be
`^{enter}{home}{delete}/invite {enter}`

Ctrl+enter, picks up @player
home goes to char[0]
delete, deletes the @ and then writes "/invite " with a blank space

Thanks.

**Comment by redSol** [comment]
Kicking yourself can be added by adding this to the shortcuts section:
{"keycode":115,"value":"{Enter}/kick charactername{Enter}","Detail":"(F4) to kick yourself"},

as for the fast trade, i will look into it

**Comment by DavidAlcns** [comment]
If you can get fast trade work, you would also enable being able to put custom msgs
such as:
"Sorry that item has been sold!"
"Sorry, in a map at this moment can you wait?"

the only thing that i don't know is how are you gonna be able to do sequence of keys to hit
`^{enter}{home}{delete}/invite {enter}`

But anyways thanks a lot for the fast kick

**Comment by redSol** [comment]
added, to add it to your current config you can do the following:
Keycode is F6
`{
      "keycode": 117,
      "value": "{invite}",
      "position": null,
      "ctrl": false
    },`
