### ISSUE TITLE
Rounding error when calculating minimum values

### ISSUE THREAD

**Issue by JusKillmeQik** [redSol/PoeTradeSearchEN#22]
For this item:

```
Rarity: Unique
Alberon's Warpath
Soldier Boots
--------
Armour: 295 (augmented)
Energy Shield: 17
--------
Requirements:
Level: 49
Str: 47
Int: 47
--------
Sockets: B 
--------
Item Level: 83
--------
16% increased Strength
Adds 1 to 80 Chaos Damage to Attacks
+207 to Armour
+9% to Chaos Resistance
20% increased Movement Speed
+1 to maximum number of Skeletons
--------
Alberon walked among the accursed,
and they welcomed him.
```

The average for chaos damage to attacks is 40.5, but your code rounds to 41. Since that is over the highest it can ever go it shows no results. My suggestion is either to round down or just leave the 40.5 since that is supported by the official trade site.

**Comment by saveriodesign** [comment]
This problem also applies to stats like raw +% crit or % of max life regen, which are so low that integer rounding isn't practical.

**Comment by redSol** [comment]
should be fixed now
