### ISSUE TITLE
BUG: with "always_on_top": false, and having it unfocus, if you click on it, it won't focus again unless you click on taskbar.

### ISSUE THREAD

**Issue by DavidAlcns** [redSol/PoeTradeSearchEN#26]
#21 
Proof: [gif.](https://i.imgur.com/ku1PBdS.gifv)

Edit: Or if you have it unfocus, and you ctrl + c an item, it won't focus again (intended?)

**Comment by AndreiEnache** [comment]
Fixed in #29
