### ISSUE TITLE
Automatically detect corruption status of item

### ISSUE THREAD

**Issue by AndreiEnache** [redSol/PoeTradeSearchEN#27]
Wondering if it could be possible to automatically detect the corrupted status of a certain item.
I tried price-checking pair of Shaper's Touch but it didn't properly detect the non-corrupted status.

**Comment by AndreiEnache** [comment]
I took the liberty to fix this in #28 
If the config does not specifically say "yes" or "no" for auto_select_corrupt it includes the item corruption status in the search.

**Comment by redSol** [comment]
thanks!
