### ISSUE TITLE
Map Modifiers Highlight

### ISSUE THREAD

**Issue by JusKillmeQik** [redSol/PoeTradeSearchEN#3]
This is another feature of AutoHotKey that was super valueable. When you select a rare map all of the mods are loaded already. Now just highlight the mods that a user selected as dangerous in a config file. So for example if my character cannot run reflect maps, if a phys or ele reflect mod shows up it would be highlighted red in the brief page.

**Comment by redSol** [comment]
thanks for the suggestions, added most of them.
