### ISSUE TITLE
Hide identical listings from the same account or older than a week

### ISSUE THREAD

**Issue by JusKillmeQik** [redSol/PoeTradeSearchEN#33]
Price fixers often flood the bottom of the results with low ball offers. If someone has 30 listings, ideally only one of them would show up for a non-currency item.

Also the ability to remove items that have been listed for over a week.

Thanks!

**Comment by DavidAlcns** [comment]
Hiding items that had been listed for over a week makes no sense as you might find something that no one wanted to buy, but perfectly fits your build and is +1 week older

**Comment by TheOne320** [comment]
I also want to hide multiple listings of items from the same person.

**Comment by JusKillmeQik** [comment]
> Hiding items that had been listed for over a week makes no sense as you might find something that no one wanted to buy, but perfectly fits your build and is +1 week older

This tool is used for price checking an item, not finding something for your build. If something has been listed for over a week it's clearly outdated and not priced to sell. On the off chance that it's the only comparable item you could turn off the time limit or go to the official site to get all of the results. But for average pricing information, old listings are generally outliers.

**Comment by DavidAlcns** [comment]
Makes sense! but would code an option to disable/enable

Regarding multiple listing, that's a yes for me, if it's possible!

**Comment by redSol** [comment]
Added an option for it, thanks for the suggestion
