### ISSUE TITLE
Poe Prices API call

### ISSUE THREAD

**Issue by JusKillmeQik** [redSol/PoeTradeSearchEN#4]
Many users don't know what mods on a rare item are even worth searching over. PoePrices returns an estimate of a rare item's price as well as the mods that were used to determine that price. A third tab could be used similar to "brief" and "detailed" that was just "estimate" and would show the price and distribution.

https://www.poeprices.info/

**Comment by JusKillmeQik** [comment]
I really appreciate all the work you've done on this project! This is the last piece to make this replace TradeMacro for me. I did some leg work for you to make it easy.

All you need to do is take the exact item text:

```
Rarity: Rare
Armageddon Dash
Crusader Boots
--------
Quality: +20% (augmented)
Armour: 174 (augmented)
Energy Shield: 42 (augmented)
--------
Requirements:
Level: 70
Str: 62
Dex: 111
Int: 155
--------
Sockets: G-B-B-B 
--------
Item Level: 86
--------
+39 to Strength
+24 to Armour
+11 to maximum Energy Shield
+45 to maximum Mana
35% increased Movement Speed
+19% to Fire and Cold Resistances (crafted)
```

And Base64 Encode it:

UmFyaXR5OiBSYXJlCkFybWFnZWRkb24gRGFzaApDcnVzYWRlciBCb290cwotLS0tLS0tLQpRdWFsaXR5OiArMjAlIChhdWdtZW50ZWQpCkFybW91cjogMTc0IChhdWdt
ZW50ZWQpCkVuZXJneSBTaGllbGQ6IDQyIChhdWdtZW50ZWQpCi0tLS0tLS0tClJlcXVpcmVtZW50czoKTGV2ZWw6IDcwClN0cjogNjIKRGV4OiAxMTEKSW50OiAxNTUK
LS0tLS0tLS0KU29ja2V0czogRy1CLUItQiAKLS0tLS0tLS0KSXRlbSBMZXZlbDogODYKLS0tLS0tLS0KKzM5IHRvIFN0cmVuZ3RoCisyNCB0byBBcm1vdXIKKzExIHRv
IG1heGltdW0gRW5lcmd5IFNoaWVsZAorNDUgdG8gbWF4aW11bSBNYW5hCjM1JSBpbmNyZWFzZWQgTW92ZW1lbnQgU3BlZWQKKzE5JSB0byBGaXJlIGFuZCBDb2xkIFJl
c2lzdGFuY2VzIChjcmFmdGVkKQo=

Then you just call:

https://www.poeprices.info/api?l=Metamorph&i=

with the encoded data at the end.

If all you had was the min/max and currency from the first result that would be a huge help. But if you could include the pred_explanation by name and percentage in another tab that would be extra helpful!

**Comment by redSol** [comment]
Thanks for the information, I'll look into it :)

**Comment by redSol** [comment]
Added.
