### ISSUE TITLE
F1 triggering something

### ISSUE THREAD

**Issue by kruggles482** [redSol/PoeTradeSearchEN#5]
F1 in game does something with the chat and I'm not sure what it does as there's nothing in the readme or the config about an F1. Running in admin, win10, default config. I can't tell what It's trying to type into the chat but I can't seem to disable it

**Comment by redSol** [comment]
It is typing /oos in chat, it's my bad that I forgot to note that I changed the /oos shortcut to F1.
If you would like to disable it or change it, go to the config file and look for the oos command and set it to whatever you like or set it to 0 if you would like to disable it

**Comment by kruggles482** [comment]
Alright thanks. I changed keycode to 113 to get the expected result. Appreciate the fast reply and the work you're doing.
