### ISSUE TITLE
Update Syndicate and Temple default images

### ISSUE THREAD

**Issue by JusKillmeQik** [redSol/PoeTradeSearchEN#7]
I've replaced the images myself but for newer players it could be good to include an English image by default.

https://wraeclast.com/#betrayal has a great syndicate image that they update every league that could replace PoeTradeSearchEN/_POE_Data/Syndicate_0.jpg

There aren't a lot of good updated Temple references but this one https://imgur.com/TpsYIYd does a decent job and might help new players if it replaced PoeTradeSearchEN/_POE_Data/Temple_0.jpg

Also, for what it's worth I would name the images betrayal.png and incursion.png because that's what the other tools use.

**Comment by redSol** [comment]
added
