### ISSUE TITLE
How can I configure selected mods ?

### ISSUE THREAD

**Issue by vadash** [redSol/PoeTradeSearchEN#9]
Here is example I am using

`	"checked":[
			{"id":"Belts/","text":"# to Strength"},
			{"id":"Jewels/Amulets/Rings/Belts/Quivers/Armours/","text":"#% to Fire Resistance"},
			{"id":"Jewels/Amulets/Rings/Belts/Quivers/Armours/","text":"#% to Cold Resistance"},
			{"id":"Jewels/Amulets/Rings/Belts/Quivers/Armours/","text":"#% to Lighting Resistance"},
			{"id":"Jewels/Amulets/Rings/Belts/Quivers/Armours/","text":"#% to Chaos Resistance"},
			{"id":"Jewels/Amulets/Rings/Belts/Quivers/Armours/","text":"#% increased Attributes"},
		],`

and it wont detect half the mods. Any way to specify if its implicit / crafted ?

**Comment by redSol** [comment]
Which mods are you having trouble with it detecting? have you tried restarting the program after putting those values in your config?

**Comment by vadash** [comment]
![image](https://user-images.githubusercontent.com/1397582/72108205-174df880-3344-11ea-84b3-fed5804739dd.png)
Both +strength here. Only attributes worked. Yes I did restart

**Comment by redSol** [comment]
Ah, I guess its a problem with modifiers that are not explicit/pseudo, i'll look into it right now

**Comment by vadash** [comment]
Thanks!

**Comment by redSol** [comment]
Problem has been solved in the next update, please have a look at it
Make sure you either replace your config file, or at least the checked mods part.
